import{addDoc,collection,doc,getDocs,query,serverTimestamp,where,writeBatch,type DocumentReference,type Firestore}from'firebase/firestore';
import type{User}from'firebase/auth';
export type SavedAddress={id:string;ref:DocumentReference;fullName:string;phone:string;addressType:string;houseNo:string;street:string;landmark:string;area:string;city:string;pincode:string;state:string;country:string;deliveryNote:string;latitude:number|null;longitude:number|null;isDefault:boolean;isActive:boolean};
export type AddressInput=Omit<SavedAddress,'id'|'ref'|'isDefault'|'isActive'>;
export const SELECTED_ADDRESS_KEY='spotc_selected_address_id';
const t=(v:unknown)=>typeof v==='string'?v.trim():v==null?'':String(v).trim();const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:null};
function mapAddress(id:string,ref:DocumentReference,d:Record<string,unknown>):SavedAddress{return{id,ref,fullName:t(d.full_name)||t(d.customer_name),phone:t(d.phone)||t(d.customer_phone),addressType:t(d.address_type)||'Home',houseNo:t(d.house_no),street:t(d.street),landmark:t(d.landmark),area:t(d.area),city:t(d.city),pincode:t(d.pincode),state:t(d.state)||'Tamil Nadu',country:t(d.country)||'India',deliveryNote:t(d.delivery_note),latitude:n(d.latitude),longitude:n(d.longitude),isDefault:d.is_default===true,isActive:d.is_active!==false}}
export const formatAddress=(a:SavedAddress)=>[a.houseNo,a.street,a.landmark,a.area,a.city,a.pincode].filter(Boolean).join(', ');
export async function loadUserAddresses(db:Firestore,user:User):Promise<SavedAddress[]>{const snaps=await Promise.all([getDocs(query(collection(db,'UserAddresses'),where('user_uid','==',user.uid))).catch(()=>null),getDocs(query(collection(db,'UserAddresses'),where('user_ref','==',doc(db,'Users',user.uid)))).catch(()=>null),getDocs(query(collection(db,'UserAddresses'),where('user_ref','==',doc(db,'users',user.uid)))).catch(()=>null)]);const unique=new Map<string,SavedAddress>();for(const snap of snaps)for(const d of snap?.docs??[]){if(unique.has(d.id))continue;const a=mapAddress(d.id,d.ref,d.data());if(a.isActive)unique.set(d.id,a)}return[...unique.values()].sort((a,b)=>a.isDefault===b.isDefault?a.addressType.localeCompare(b.addressType):a.isDefault?-1:1)}
export async function setDefaultAddress(db:Firestore,user:User,addresses:SavedAddress[],selected:SavedAddress){const batch=writeBatch(db);for(const a of addresses)batch.update(a.ref,{is_default:a.id===selected.id,updated_at:serverTimestamp()});await batch.commit();sessionStorage.setItem(SELECTED_ADDRESS_KEY,selected.id)}
export async function createAddress(db:Firestore,user:User,input:AddressInput,existing:SavedAddress[]){const batch=writeBatch(db);for(const a of existing)batch.update(a.ref,{is_default:false,updated_at:serverTimestamp()});await batch.commit();const ref=await addDoc(collection(db,'UserAddresses'),{user_uid:user.uid,user_ref:doc(db,'Users',user.uid),full_name:input.fullName,phone:input.phone,address_type:input.addressType,house_no:input.houseNo,street:input.street,landmark:input.landmark,area:input.area,city:input.city,pincode:input.pincode,delivery_note:input.deliveryNote,latitude:input.latitude,longitude:input.longitude,state:input.state||'Tamil Nadu',country:input.country||'India',is_default:true,is_active:true,created_at:serverTimestamp(),updated_at:serverTimestamp()});sessionStorage.setItem(SELECTED_ADDRESS_KEY,ref.id);return{id:ref.id,ref,...input,isDefault:true,isActive:true} satisfies SavedAddress}
export function selectedAddressFrom(addresses:SavedAddress[]){if(!addresses.length)return null;const id=typeof window==='undefined'?'':sessionStorage.getItem(SELECTED_ADDRESS_KEY);return addresses.find(a=>a.id===id)||addresses.find(a=>a.isDefault)||addresses[0]}
